# If these are enabled they will be used instead of any instructions
# they may mask.  For example, alias rm='rm -i' will mask the rm
# application.  To override the alias instruction use a \ before, ie
# \rm will call the real rm not the alias.

# Interactive operation...
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Show human readable figures
alias df='df -h'
alias du='du -h'

# Show differences in colour
alias ls='ls --color=auto'
alias grep='grep --color'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Some shortcuts for different directory listings
alias ll='ls -alF'
alias la='ls -A' # all but . and ..
alias l='ls -CF'
alias l.='ls -d .*'

# Move up quickly
alias ..='cd ..'
alias ...='cd ../..'

# return immediately without waiting
alias ec='emacsclient -n'
